### ISSUE TITLE
Share Location

### ISSUE THREAD

**Issue by samitalalchan** [Skjutsgruppen/skjutsgruppen-reactnative#239]
@MattiasJay We are on our way to start on **Share location** functionality, so we like to be crystal clear even before we begin. I found this in doc **Can only be pressed if participant has already commented on the ride - very important** . Except this i have few queries :)

1. Is the design of share Location final as in the Old design as below or shall we expect a new design.
https://projects.invisionapp.com/d/main#/console/10599238/225963503/preview
2. If a user shares his location in a  group/trip, Is it visible to everyone in the group/trip.
3. Can he cancel the shared location functionality before the share time in over.
    3a. If so how and where...

**Comment by MattiasJay** [comment]
Hi @anjhero @anjesh @umuieme  @shresthaKiran ,

great to see the progress with sharing location. We stil have a way to go, but we're getting there. 

1. If you look at the conversation with @samitalalchan above, there's an important design destinction that is not yet correctly implemented. As you can see above, where ever you press share location 

> "They all open the same menu with three suggestions".

Currently when asked to share location by the app, the map first opens with the three suggestions above it. Also it is white background, which is wrong. This should not happen. The three suggestions should open with dark background on the same place as the conversation. Then you choose time and then you come to the map.

The dark background is off course very important. It should feel native.

2. When sharing web version of share location, nothing happens when pressning ”see our ride” (web version of the ride card should open)

3. Also there's some obvious design flaws in web version, like circles not being circles 😄 

4. The menu of who to share with have two errors. 

a) It should not say "Share to the movement" since that is not what is happening. That is even scary since you want to specifically know who you are sharing with when sharing location in a single ride. When sharing in **_a group_** this is ok, but not here. 

b) The error message below is wrong since I may want to only share to friends and family on Facebook, Twitter or by copying link without sharing to participants in the ride. So, it should not be an error if I'm not selecting participants:

![image from ios](https://user-images.githubusercontent.com/10048880/48317851-7f963280-e5f8-11e8-8200-c4c0f68fc486.png)

**Comment by ruchidhami** [comment]
This issue has been resolved.
