### ISSUE TITLE
Search: location names showing postal codes

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#398]
1) When trying to search from "Grönsakstorget" I can choose Grönsakstorget here. That is good:

![photo_2018-04-25_09-10-24](https://user-images.githubusercontent.com/10048880/39230924-a61999ac-4868-11e8-9af0-6818010620cb.jpg)

----------

2) But then it doesn't say "Grönsakstorget", it says "411 17 Gothenburg". This is wrong:

![photo_2018-04-25_09-10-21](https://user-images.githubusercontent.com/10048880/39230959-c0b5bf52-4868-11e8-8b30-3957534e1eb4.jpg)

---------------

3) ...and then the search result first shows rides and then public transportation, like this. It's wrong, I'll explain more below

![photo_2018-04-25_09-10-18](https://user-images.githubusercontent.com/10048880/39231010-e943358a-4868-11e8-8b28-60d86fe379e8.jpg)

This should not be the case. IF Public Transportation and rides are both selected they should be shown within the same date, like this: https://projects.invisionapp.com/d/#/console/12489615/267159309/preview#project_console

Maybe there's a confusion here about _groups_, @anjhero @anjesh @samitalalchan ?

**Comment by anjesh** [comment]
@shresthaKiran can you post the API  url and the response here that's giving the above result? We need to see if this is under our control or not. If not, we might need to skip this issue of showing postal codes.

**Comment by shresthaKiran** [comment]
When a user types the place name (Grönsakstorget), https://maps.googleapis.com/maps/api/place/autocomplete/json?&input=Gr%C3%B6nsakstorget&key=xxxxxxxxxxxxxxxxxx search place google API is called and then we display all the values of description from the following json:
`{
predictions: [
{
description: "Grönsakstorget, Gothenburg, Sweden",
id: "97451ec4bab5bdfbc2385e70ebf3a92f009925f1",
matched_substrings: [
{
length: 14,
offset: 0
}
],
place_id: "EiNHcsO2bnNha3N0b3JnZXQsIEdvdGhlbmJ1cmcsIFN3ZWRlbg",
reference: "CjQnAAAAP36w-OOuL4SHNrO_3axPWwWB9mRyVDNnOoiWJDV586nvP67oATAZq9XBHaBb7-3mEhCwF6cYUHUz0MtYUUjLQ8INGhRw-mrWeQhmGIoBVj0yZE5E7jq-tA",
structured_formatting: {
main_text: "Grönsakstorget",
main_text_matched_substrings: [
{
length: 14,
offset: 0
}
],
secondary_text: "Gothenburg, Sweden"
},
terms: [
{
offset: 0,
value: "Grönsakstorget"
},
{
offset: 16,
value: "Gothenburg"
},
{
offset: 28,
value: "Sweden"
}
],
types: [
"route",
"geocode"
]
},
{
description: "Grönsakstorget, Gothenburg, Sweden",
id: "a9d324cb44b4cf478612fe4e3e950fda86ab34ea",
matched_substrings: [
{
length: 14,
offset: 0
}
],
place_id: "ChIJuUcvTG_zT0YROknfgRP2ugU",
reference: "CkQxAAAASMV00Q_3fyU0xiDmuZFAm5IN-J9cLWaXangdk96bDOFsu5vfi0hukhs6fmwT_KEt68Wr0_Wd7Z__l3Z97BjIsxIQLc_ZgJN3rXB81IqTAm_FRBoU6pImrXId3SmvX_1PyrRrGCCczL4",
structured_formatting: {
main_text: "Grönsakstorget",
main_text_matched_substrings: [
{
length: 14,
offset: 0
}
],
secondary_text: "Gothenburg, Sweden"
},
terms: [
{
offset: 0,
value: "Grönsakstorget"
},
{
offset: 16,
value: "Gothenburg"
},
{
offset: 28,
value: "Sweden"
}
],
types: [
"transit_station",
"point_of_interest",
"establishment",
"geocode"
]
},
{
description: "Grönsakstorget, Västervik, Sweden",
id: "af50e08d8867891404e5d1f6c1c5ac1dea7b89bd",
matched_substrings: [
{
length: 14,
offset: 0
}
],
place_id: "EiNHcsO2bnNha3N0b3JnZXQsIFbDpHN0ZXJ2aWssIFN3ZWRlbg",
reference: "CjQnAAAAP04pi_GTRsgwfhuWUJf_NdaFmayPDeWHWSHuoAz3n632478xWpMLaoNSVffk-bvREhBNRu9ya0RNInYpVgFtudK2GhQyyEl9H3QJuAxz18XJIEthPFjg7Q",
structured_formatting: {
main_text: "Grönsakstorget",
main_text_matched_substrings: [
{
length: 14,
offset: 0
}
],
secondary_text: "Västervik, Sweden"
},
terms: [
{
offset: 0,
value: "Grönsakstorget"
},
{
offset: 16,
value: "Västervik"
},
{
offset: 27,
value: "Sweden"
}
],
types: [
"route",
"geocode"
]
},
{
description: "Grönsakstorget, Grönsakstorget, Gothenburg, Sweden",
id: "8aa0b9c689b5fd538bde958af4602ae0f5b7ac80",
matched_substrings: [
{
length: 14,
offset: 0
}
],
place_id: "ChIJWZZaQ2_zT0YReV_n3yq48pQ",
reference: "ClRDAAAAyrcob1NZvFbYH35iio7zKH9FgywTL0x_JO0lE3DjhspdFRk-O2e0vcQ8hNr0JmM7_MakuN_FWs2eK8Wuk-xpKVDUBdDrFykEuDm8em58dd4SEIE6SPjoplLL5oF4S6vcYYEaFByUk_tKCxahzCpWF18I6P3QW665",
structured_formatting: {
main_text: "Grönsakstorget",
main_text_matched_substrings: [
{
length: 14,
offset: 0
}
],
secondary_text: "Grönsakstorget, Gothenburg, Sweden"
},
terms: [
{
offset: 0,
value: "Grönsakstorget"
},
{
offset: 16,
value: "Grönsakstorget"
},
{
offset: 32,
value: "Gothenburg"
},
{
offset: 44,
value: "Sweden"
}
],
types: [
"establishment"
]
}
],
status: "OK"
}`

So, if the user selects 2nd option, then we take its place id (ChIJuUcvTG_zT0YROknfgRP2ugU) and we call another google api (https://maps.googleapis.com/maps/api/place/details/json?key=xxxxxxxxxxx&placeid=ChIJuUcvTG_zT0YROknfgRP2ugU) which will give the details of the place

`{
html_attributions: [ ],
result: {
address_components: [
{
long_name: "Sweden",
short_name: "SE",
types: [
"country",
"political"
]
},
{
long_name: "Inom Vallgraven",
short_name: "Inom Vallgraven",
types: [
"sublocality_level_1",
"sublocality",
"political"
]
},
{
long_name: "Gothenburg",
short_name: "Gothenburg",
types: [
"postal_town"
]
},
{
long_name: "Västra Götaland County",
short_name: "Västra Götaland County",
types: [
"administrative_area_level_1",
"political"
]
},
{
long_name: "411 17",
short_name: "411 17",
types: [
"postal_code"
]
}
],
adr_address: "<span class="postal-code">411 17</span> <span class="locality">Gothenburg</span>, <span class="country-name">Sweden</span>",
formatted_address: "411 17 Gothenburg, Sweden",
geometry: {
location: {
lat: 57.70251029999999,
lng: 11.9647519
},
viewport: {
northeast: {
lat: 57.7038592802915,
lng: 11.9661008802915
},
southwest: {
lat: 57.70116131970849,
lng: 11.9634029197085
}
}
},
icon: "https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png",
id: "a9d324cb44b4cf478612fe4e3e950fda86ab34ea",
name: "Grönsakstorget",
photos: [
{
height: 1200,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/102751562062352999304/photos">biketommy999</a>"
],
photo_reference: "CmRaAAAAk2wl4pfwB886MZiX25ULbqXTFLx0lSlPXNzDM83JlGZWSvo0EDLpiZ0_Ifq7jXllsDc1Ehpf8LyhxDPUQMFFZBDUUnnnNXnXj_x5S_0c6V2bNCKY5jEtgpAWVh6JXCrzEhAGSg0UzyAeOjJzbaCDrTruGhSlRAWTu7ETa88aKpa5kCGRbi8xcw",
width: 1600
},
{
height: 1836,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/104117033379966518746/photos">Jacky Wong</a>"
],
photo_reference: "CmRaAAAA7H6WDjp39n3HWfp-kXAQnuWTiMMaZhL4fvWQCdapab-xYPF6k9KJUruV6aWVA4lYgQl3Mz1YYlMrniEWmMlopfSyVX3pZA1ubRjMyWTdGomnNKjtyoPPwjbYZxATEUzIEhDMpiiOoy-KxrSJGFscStNZGhTFxTkOxkcyoLwbrpBLugE-cJhsbg",
width: 3264
},
{
height: 3833,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/103978372839234177112/photos">Mikael Levin</a>"
],
photo_reference: "CmRaAAAA1LJx-MTGFhEM-_zYdx-owLVBig7yWca5fik9uVw3FAkRJ5klJfeAGK5BpA_DnAmC2Ho2Di6ei7rrk26a9aJKvVsfrT38oWtefVjXpFZr3TVG-02jscXLEs9kSTxJKZKAEhBpqyScnB3qAPTXtTX0qV8fGhQA2pjgIqECtUTiGBSp6jgpvgTF3A",
width: 6000
},
{
height: 3168,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/113586529356339738871/photos">Gabo Blancas</a>"
],
photo_reference: "CmRaAAAAPpf1WTCwx6w-MbhByM2-BU4hPpof2FPrLNm0-oJ9nSleXaDY9io6pOV_OfKt6uTnU3eV64JGMGH_6Wa5la1Y1N3KHIf1l6FaEAPPWomv5ehPDgG47hFwcSBP5ivFneUiEhBJ5pm7yrA8TdwfwJ_GNipJGhQWvcxJBx7YVeB_5E_Gs-HI02OyTQ",
width: 4752
},
{
height: 1836,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/104117033379966518746/photos">Jacky Wong</a>"
],
photo_reference: "CmRaAAAAa8A_lbiO13I-JRgnOZQTjbm-Hm6tLJPzoPznCuYXulvZzzdYL4X_X2QFSY0HmyIIPgjCAgBpPqZa1eF7uz41tZg4NP77QRCmHatMvE_9k6Jjw3A9A4qnTirNZ2IaxRKLEhDwRm9UAMDUqwAIWfy6YooLGhTOuqFdo9yPrbySEYC25RCIje5XJw",
width: 3264
},
{
height: 4048,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/100705890708823647819/photos">Alexander Williamson</a>"
],
photo_reference: "CmRaAAAAzScX_paI-znESnEIIEmbefxPyBQlmEKRDTZQ3GISOmi9cN8jLGjXWBeZPko_7yHr7Rap84eD-c9wXYlqm61BbPgQKKhuJpXRRkcZWZNHSqWSm2sGzyaW_42554RatLuREhCmQtZswFkpt8tfofqz5GTcGhS8jTkHpwEieSaM6_rpuIzpB3bYCg",
width: 3036
},
{
height: 2988,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/115155074705455474281/photos">Gunilla Ludvigsson</a>"
],
photo_reference: "CmRaAAAABP-oDiZGUH7p7fyuMFA3rxOTgN9rV1suM0Pxqh_IyziMzfBjsHHGpIL4mlW6ASdoppTVIiGMv6rbbMni3moVwCI0OBFORu2wgi6IgyyMY7yKJZT8LLr8RtGpAakyudbmEhBVDGLo6o7NArwZIvm7EFnWGhQyf2HS8K7_h74vC52k5EiVaynm1w",
width: 5312
},
{
height: 4608,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/102423806762436462935/photos">sean5338</a>"
],
photo_reference: "CmRaAAAArdbsvn2Z8u61psSruEDinVUNTK2WfiXUUBHLvqHkirxODeyBlwCYe4Z2x3ZBozdX1UwFZfrEGGEb0zEPbAqxbEeRbXw2JDc3Y96zmFZXPM1JxDpPSqgBLqC7oGfZKvJ_EhCFYvkbjBgnnutY9cYC5TMXGhRSquNlbwxcFjfJTdjgrOtGgbHHlQ",
width: 2592
},
{
height: 2988,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/105204660617823543247/photos">Oleg Baranov</a>"
],
photo_reference: "CmRaAAAAyf603Fw9MafL9Ks0jCCoBFYYgD_UUCfV4P-zHBssbmEOy2k2NEQg6ihZIQp4WmXmdrn_2zeqfd9z8ykqAoYgz2fq_SqlltMAeIWwgs3KAJpSf5CiyuGYCEVAq_ySJTM6EhBmdMXa_Z91jVqtOnRzwpk_GhQ2doQ5RU4vWwS0WSv-4heTJFuVVA",
width: 5312
},
{
height: 2988,
html_attributions: [
"<a href="https://maps.google.com/maps/contrib/109835590724698866226/photos">Stefan Norrgran</a>"
],
photo_reference: "CmRaAAAApBG5og8zJsj4qo1SR4JOxS_SgMUBn5vxctvbSpXwYETz97GJdKsCZOfv0l4K0Q10T4zYhSNQJvGaJf8G8Ewdip26nHAXOkEzXjxCLlCdpZks93bRO_LB69NVTH71LSjOEhDKLQLQSDsq8bsnvD_tw2GTGhSOfsaxNKD7NYBdkQ0qZWJTQTgpww",
width: 5312
}
],
place_id: "ChIJuUcvTG_zT0YROknfgRP2ugU",
plus_code: {
compound_code: "PX37+2W Gothenburg, Sweden",
global_code: "9F9HPX37+2W"
},
rating: 4,
reference: "CmRRAAAAi_k-GCc0zmUkNvXrRN3FBRbG8tZqZ5yFsGbRmheuplPwP5HjH6_2n9jBxp7IQuHZoqnSzSMJAx5EjxpcSmctK3iN9o-uuqQx75C6at9CDzLivBa4Yr1HuFZ7YNKkm-qpEhAOfxzBaXO5Fg9F8SVxkWOJGhQsEfprlw8pdMStz5OZbrr_q9ehLw",
reviews: [
{
author_name: "Alexander Williamson",
author_url: "https://www.google.com/maps/contrib/100705890708823647819/reviews",
language: "sv",
profile_photo_url: "https://lh4.googleusercontent.com/-k-0LvAy9Mn8/AAAAAAAAAAI/AAAAAAAABQI/9dog1M2Th1Q/s128-c0x00000000-cc-rp-mo-ba6/photo.jpg",
rating: 3,
relative_time_description: "8 months ago",
text: "Väntkur och realtid, finns flera hållplatser med samma namn",
time: 1514577767
},
{
author_name: "Buzz Killington",
author_url: "https://www.google.com/maps/contrib/102188746431652914584/reviews",
profile_photo_url: "https://lh5.googleusercontent.com/-wwN_MmG8u-E/AAAAAAAAAAI/AAAAAAAAAAA/APUIFaMOym7mCn57L-A5j2RTjLktw_UTxQ/s128-c0x00000000-cc-rp-mo-ba2/photo.jpg",
rating: 5,
relative_time_description: "12 months ago",
text: "",
time: 1505226599
},
{
author_name: "Paolo Bonandin",
author_url: "https://www.google.com/maps/contrib/118318481982868392167/reviews",
profile_photo_url: "https://lh5.googleusercontent.com/-jxzrz-xykjw/AAAAAAAAAAI/AAAAAAAAYX8/ToM63rhKaZw/s128-c0x00000000-cc-rp-mo-ba5/photo.jpg",
rating: 4,
relative_time_description: "2 years ago",
text: "",
time: 1447944471
}
],
scope: "GOOGLE",
types: [
"transit_station",
"bus_station",
"light_rail_station",
"point_of_interest",
"establishment"
],
url: "https://maps.google.com/?cid=412912879501527354",
utc_offset: 120,
vicinity: "Sweden"
},
status: "OK"
}`. 


We separate the value of formatted_address(411 17 Gothenburg, Sweden) and only use the first value before comma due to which (411 17 Gothenburg) value is displayed to user. @anjesh

**Comment by ruchidhami** [comment]
This issue has been resolved.
