### ISSUE TITLE
App Store information for iOS app

### ISSUE THREAD

**Issue by anjhero** [Skjutsgruppen/skjutsgruppen-reactnative#407]
Login to your itunes connect account and go to *My apps > Prepare for submission* and check/ enter the required information in the form there

**Comment by MattiasJay** [comment]
For safe keeping:

### Promotional Text

We are the non-profit ridesharing movement Skjutsgruppen. When we're going the same direction we offer our spare seats to each other and share the costs equally.


### Description

We are the non-profit ridesharing movement Skjutsgruppen. We started in 2007 and consists of friends, and friends of friends, who's getting closer to each other all over the world!

When we're going the same direction we offer our spare seats to each other in buses, boats, cars, bicycles and hot air balloons. 

We share the costs of our rides equally or offer rides for free, because friends don't make money of friends.

This app is enabled by participants of the movement, our non-profit association and The Region of Västra Götaland, Sweden. The app is free to use and you can join the movement where ever you are in the world! (read more below how you can translate the app to your language and community).

In this app you can among many things:
- Offer rides
- Ask for rides
- Create groups for a specific distance, area or subject (and invite others to join)
- Discover and participate in already made groups
- Share your live location with other participants

If you're using this app in Sweden you also get public transportation among your search results. The app is open source and anyone is invited to add more public transportation data from all over the world. Feel free to join our open source project! (read more in the app)

As a non-profit movement we grow dynamically in communities all over the world. To make it easy for your community to start to rideshare we have connected an translation tool to the app so you can translate to your language very easy! (find the tool in the app).

We call this app an "self-sustaining garden". We believe in sharing equally and participants of the movement are offered to share the costs of maintaining the app if they want to, the same way as we share the costs equally when we rideshare. The app is free to use and you always choose yourself the way you would like to support the self-sustaining garden with money and/or knowledge (by example helping out with the open source project or translating the app to other languages).

Welcome to the movement!
