### ISSUE TITLE
FOAF: "friend joined" notification didn't show up 

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#468]
Is this feature broken? I have two phones (work phone and private). We I signed up with my second phone I got no notification that "My friend has joined the movement" and we are neither connected as friends, as we should be.

I made sure to first delete the app on my private phone and re-uploaded my contacts again. Still.. nothing.

**Comment by MattiasJay** [comment]
❗️ 
 We are still on this important issue: now I added a new participant; myself with my work number, and this time _nothing_ of what should happen happened; 

1) On my "real" account: I did not recieve a notification that my phone book contact (myself) has joined.

2) On my new account and old account: we are not connected as friends even though we have each other in each others phone books. ❗️ 

This is now bumped up as urgent @anjesh @anjhero @manishgs @shresthaKiran , at the same time as we will add this to the onboarding process as well.

**Comment by MattiasJay** [comment]
Hi again, I tested this again with the current version that's in App Store (not Test Flight), and this is still a problem; we did not become friends. I'm moving this back to open issues @anjhero @anjesh @manishgs and @shresthaKiran .

**Comment by shresthaKiran** [comment]
Hello Mattias, It seems your 1st account's (associated with id 1) doesn't have phone number of 2nd account (associated with id 36162), due to which your two accounts are not friends with each other. 

Could you please logout from 1st account and login again so that your latest contacts will be synced again. This time if your 1st account has contact of 2nd account, then your two accounts should be friends with each other. @MattiasJay

**Comment by anjesh** [comment]
Please reopen if still facing issue.
