### ISSUE TITLE
Subscriptions plan and modality 

### ISSUE THREAD

**Issue by umuieme** [Skjutsgruppen/skjutsgruppen-reactnative#470]
- [x] the plans amount is finalized
- [ ] names for each plan (apple needs it) are done https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/515
- [x] one user one subscription (for android and ios) is decided 

@MattiasJay  Apple in app purchase does not allow us to add custom price. We have to select from predefined prices. [https://developer.apple.com/app-store/subscriptions/App-Store-Subscription-Pricing.pdf](https://developer.apple.com/app-store/subscriptions/App-Store-Subscription-Pricing.pdf)

**Comment by MattiasJay** [comment]
Thanks @umuieme ! Could you save me some time by figuring out which prices are closest to the one we have in the design? Thanks!

**Comment by umuieme** [comment]
@MattiasJay Here are the price closest to our price tag

- 9 kr per month  for six month (54 kr)-> available 55 kr or 50 kr
- 29kr per month -> 29 available
- 49kr per month for a year(588 kr) -> 589 available
- 149 kr per month for a year (1788 kr) -> 1749KR or 1795Kr 
- 599 Kr per month for a year (7188 Kr) -> 7495 Kr

**Comment by umuieme** [comment]
@MattiasJay any update on this?

**Comment by MattiasJay** [comment]
Looks great that they are so close to what we already wanted @umuieme ! 

Let's do this: 

55 kr
29 kr
589 kr
1749 kr
7495 kr

**Comment by umuieme** [comment]
@MattiasJay  what about android in app purchase maximum limit of 3000 kr?

**Comment by MattiasJay** [comment]
Can you give me some suggestions on this @umuieme @anjesh @anjhero ? Example; could we do a combination for android, like they press two different buttons to add it up? Or should we increase the number of months for Android so it autorenews and gets up to the sum? Give me your best suggestions for this. (you can also talk with us on Slack about this if you want)

**Comment by anjhero** [comment]
@MattiasJay looks like the apple guys will not allow us to have multiple subscriptions of the same plan. That is why they want us to put the pricing plans into the same group. Please check their response to our plea: 

![image](https://user-images.githubusercontent.com/528549/45083421-85185d80-b11b-11e8-8316-259f734964e4.png)

We should either restrict the users to stick to only one plan at a time or should think of other alternatives. Let us know what you think.

**Comment by anjesh** [comment]
@MattiasJay this has been taking very long and looks like never ending for various reasons, we need to make final decisions on how to move forward. 

Here's our suggestions. 

### 1. Plans, amounts and names

55 kr - per 6 months (support 6 months)
29 kr  - per month (support 1 month)
589 kr - per year (support 1 year)
1749 kr - per year (support 1 year)
3000 kr - per 6 months (support 6 months) 

This means when we calculate the per month cost as there will be decimal numbers. Do you want to show decimal numbers or make some [design change](https://projects.invisionapp.com/d/#/console/12489615/269796575/preview) where you are showing `xx Kr per month`? 

### 2. One user one subscription

Based on apple response, an user can't do multiple subscriptions. Hence once user subscribe to one plan, other plans will be disabled. This will be applicable in both ios and android. 

----

If you have any other suggestions, please let us know by tomorrow. Otherwise lets move forward as per above list.

**Comment by MattiasJay** [comment]
I see what Apple is writing @anjesh and @anjhero , and it is reasonable. 

We will do this:
1) In accordance with Apples suggeston participants can only support with one option. 

2) Keep the orginial design. This seems to not have been Apples issue. If needed we can walk through how other in-app purchases has done it.

3) When it comes to decimals the first one, 9 SEK, is what stands out for me. To make this one with decimals would confuse our participants unesessary much. 

I suggest we do another split for the first one, like using five months instead of six, to get rid of the decimals. That would make the first one 11 SEK /month for 5 months = 55 SEK.

Any suggestions based on that?

**Comment by anjesh** [comment]
@MattiasJay I support. 

So here are the decisions. 

1. We will have following plans and amounts

> 55 kr - per 5 months (support 5 months)
29 kr - per month (support 1 month)
589 kr - per year (support 1 year)
1749 kr - per year (support 1 year)
3000 kr - per 6 months (support 6 months)

2. We will have one user one subcription. We will keep original design but the "further support" section in this [design](https://projects.invisionapp.com/d/#/console/12489615/295069413/preview#project_console) will be hidden once supported. But it will enable if the person is not longer supporting. 

3. `pending` We still need names for the plans as per plan. @anjhero has some ideas on that. @anjhero could you write those names for each plan here and Mattias will finalise those names.

**Comment by MattiasJay** [comment]
Approved 1 and 2. 

We have talked about number three and it is most likely due to the misunderstanding that Apple thinks we have many different packages. But as concluded, we don't. We actually only do one thing; support (as Apple also have stated, correctly, above).

Hence, we won't need names like this and should go back to the original design. Original design is very important and is based on how most in-app purchases does it.
For reference, @anjhero @umuieme (?) and me talked about this on the Skype meeting September 5th 2018.

**Comment by umuieme** [comment]
@MattiasJay  the subscription duration for apple in app purchase can be only
1 week
1 month
2 months
3 months
6 months
1 year
So the plan of 55 Kr per 5 month is not possible. Should we do 55 kr per 6 month?

Also there is no 3000 Kr option in app store. So need to go with 2,995 Kr per 6 month.

**Comment by MattiasJay** [comment]
@umuieme , making it six months of 55 kr will get us decimals - and that would not look good in the design as we talked about above with @anjesh .

What's the next closest amount that Apple will allow us to use, that would round of to a nice number @umuieme ?

Is it 60 kr? That would round of nicely to 10 kr / month

**Comment by umuieme** [comment]
What about 45 Kr per 3 month that would be 15 Kr per month?
589 Kr per year and 1749 Kr per year will also give decimal numbers if we convert them to per month price. Should we show per month price for them as well?

**Comment by umuieme** [comment]
@MattiasJay where are we on these issue?

**Comment by MattiasJay** [comment]
As stated above, the most important to not have decimals is the first number @umuieme . Is 60 kr available? If it is, then choose that for six months (10 kr each month). The pedagogical part here is the "10 kr/month" that should be as small as possible of a number (15 is in the wrong direction).

Rest can have decimals.

And yes, the original design with per month price is what we need. To really see if this looks weird or not, can you send me a screen shot?

**Comment by umuieme** [comment]
@MattiasJay  There is no 60 Kr. We can do 30 Kr for 3 month which satisfies all conditions. As for design of decimal in yearly plan i will send you screenshot.

**Comment by MattiasJay** [comment]
I saw the screenshot now @umuieme . Talking to you on Slack now about it.

**Comment by MattiasJay** [comment]
Meeting on september 25th:

- Support one month. 10 kr. Auto renewed. (delete "per month" text)

- Support one month. 29 kr. Auto renew. (delete "per month" text)

- Support one year. 589 kr. Auto renew. (delete "per month" text)

- Support one year. 1749 kr. Auto renew. (delete "per month" text)

- Support six months. 2995 kr. Auto renew. (delete "per month" text)

**Comment by anjesh** [comment]
Good for closing - the remaining issues with garden is here https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/568
