### ISSUE TITLE
Confusion in "forget password" flow

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#477]
This just happened: when forgotten the e-mail you used, but remember your phone number - you can only retrieve password with ...e-mail... that you have forgotten.

**Comment by shresthaKiran** [comment]
@MattiasJay For now we will be adding a screen where user can get their partial email (for example: h**@skjutsgruppe.nu) by entering the associated phone number. The user need to contact to support if they have no longer access to the email.

Another workflow: Instead of displaying partial email, user will send a sms with a specific keyword (like **Forgot Password**) and our system will generate a random password and display the password to the user in the app.

/cc @anjhero

**Comment by shresthaKiran** [comment]
@MattiasJay  Any update on this?
