### ISSUE TITLE
The super long lag in "Messages and groups" section is a large and growing problem for our participants

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#565]
It takes a very long time for new messages to appear in the notification center "Messages and groups". I've had conversations with frustrated participants today who just think no one is answering their rides and/or can't find these notifications. As we know this is due to the super long lag in "Messages and groups". Even though an participant gets an push notification about for example a new comment this is not directly reflected in "Messages and groups". @ruchidhami @anjhero @anjesh 

This participant made her ride many days ago, and it is over. When I comment her ride she does not see this in her notification center "Messages and groups". We waited for five minutes and still nothing: https://skjutsgruppen.nu/t/43895

Could there be an issue that IF comment on old ride, THEN no notification in notification center @ruchidhami @anjhero ?

**Comment by ruchidhami** [comment]
@MattiasJay  I had checked all type of notifications in detail . **There is no any lag issue**. It works perfectly but however it seems confusion. 

I had created a short video for **friend request sent, group joined and comment on group**. Please have a look on this.  

1. Notification for friend request seems works perfectly. Have a look on below short video. 

![friend_request](https://user-images.githubusercontent.com/13533382/52999564-3ef75200-344e-11e9-936b-1dd7291c877e.gif)


2. As one of the user has joined the **ramilo sansar** group , and i got the notification of that , since I am also the participant of that group. 

 ![joined_group](https://user-images.githubusercontent.com/13533382/52993671-1ca90880-343d-11e9-81e3-326e3ed69ce4.gif)

3. Now the point is here, User **Saugat** has commented on the same group **ramilo sansar** and notification appears in bundling. Since, there is no specific message like **someone has commented or someone has joined the group**. Due to bundling logic , if same user comments multiple times then it looks like nothing happens and count remains the same . If another user comments on the same group it will also bundle on the same notifications and just the count increases.

  ![bundle](https://user-images.githubusercontent.com/13533382/52997831-ba0a3980-3449-11e9-943b-61c52fd7feb3.gif)

**Comment by anjesh** [comment]
Yes the messages take a while to load because there's lot of processing happening there - like pulling the message, and then bundling them and there are lots of messages. the data volume is high which is causing this. One thing we will be trying is to have a loading bar in "new" messages so that user don't feel like waiting. Unless you have other ideas? @MattiasJay

**Comment by MattiasJay** [comment]
Thanks for aknowledging this @anjesh . 

On our meeting we talked about this idea:
1) Load the messages first and then
2) After clearly loaded send e-mail and push notification that there's new messages

This in combination with loading bar sounds good.

**Comment by ruchidhami** [comment]
Hello @MattiasJay , I am sorry I didn't get you on this. 
**After clearly loaded send e-mail and push notification that there's new messages** 
Sending email and push notifications is not based on any messages loading. I mean sending push notifications and email are totally the different thing , we can't control from our side . 
For  e.g If the user hasn't open the app for few days, doesn't mean that he/she will not receive any notifications or email.

**Comment by anjesh** [comment]
@MattiasJay waiting for your clarification?

**Comment by MattiasJay** [comment]
E-mail can probably be sent as it is, and is probably not a problem. The problem is that the participant gets a push notification and then finds nothing in the notification center.

I suggest this: 1) the system loads a message in the notification center in the background . 2) The system notice that a new message is loaded in the notification center . 3) Push notification is sent about this new thing.

So, like this: IF message loaded in background in notification center THEN send push notification.

**Comment by MattiasJay** [comment]
This seems to be sufficiently solved now @ruchidhami , @anjhero and @anjesh with todays update. The lag is still there and something we need to work on in the future, but the loading animation will do for now.
