### ISSUE TITLE
Add "About the movement" section

### ISSUE THREAD

**Issue by anjesh** [Skjutsgruppen/skjutsgruppen-reactnative#572]
This is what the spec says
```
Extended version of the “About section” that already exists on www.skjutsgruppen.nu
This  maybe be cutted up to several pages.
```

@MattiasJay could you add more info on what you are looking for here by today? If i understand you correctly from last call, it's adding one menu option and link to google docs. Please share the google docs as well.

@ruchidhami @saugatmaharjan

**Comment by MattiasJay** [comment]
Correct, this is one of the things we will make easier at the moment, instead of the detailed version we originally had planned.

We will simply link to this document, that opens in the default browser of the phone: https://docs.google.com/document/d/1WZECcrD_Qw9dYoLA-uSr8cxCluRjtNKP0gzVXFaxieg/edit?usp=sharing

@anjesh @ruchidhami @saugatmaharjan

**Comment by ruchidhami** [comment]
@MattiasJay  This has been implemented.
